### ISSUE TITLE
German search engines??? whre i find it, all only amrican or english websites

### ISSUE THREAD

**Issue by BlackEagleGermany** [NumeriusNegidius/Context-Search#35]
German search engines??? whre i find it, all only amrican or english websites

**Comment by NumeriusNegidius** [comment]
Just go to any german site with a search engine and right click in the search field and add the keyword search bookmark in the Searches folder.

**Comment by BlackEagleGermany** [comment]
"i should "add the keyword search bookmark" in the searches folder ?!"
doesnt work!
what ?
can you write it correct?

 in what?

**Comment by phonphen** [comment]
try change location in bookmark to
https://www.google.de/search?q=%s&hl=de

**Comment by BlackEagleGermany** [comment]
That is only one, i have too!
YouTube and other???
eBay
Google Maps
ebay Kleinanzeigen ...

**Comment by NumeriusNegidius** [comment]
This doesn't seem to be an issue relating to Context Search WebExtension. Make sure "Choose your preferred language for displaying pages" in Firefox Options are set to German. Either that or the websites you are trying to access are set to display the US version for one reason or another. 

I'm closing this issue since it isn't a bug in Context Search WebExtension.
