### ISSUE TITLE
Updates to Context Search 0.9.1 are not found by addons.mozilla.org

### ISSUE THREAD

**Issue by grahamperrin** [NumeriusNegidius/Context-Search#44]
0.9.1 on (Tier-3) FreeBSD-CURRENT. 

I had no idea that 1.0.3 was available until I stumbled across https://addons.mozilla.org/addon/context-search-we/

**Comment by NumeriusNegidius** [comment]
That's odd. Seems like either a problem on AMO's part (unless you've disabled automatic updates). 

Looking at the statistics, there's only 1 user of 0.9.1 during the last fortnight (which probably was you), so it seems like an isolated problem. I'm closing this issue since I have no influence over AMO.

**Comment by grahamperrin** [comment]
Thanks. 

I disabled automatic updates long ago (to avoid losses of functionality with various extensions). 

The update to Context Search never appeared in response to a manual check. 

I'm now at 1.0.3, installed manually from AMO.
