### ISSUE TITLE
Support keyword searches with POST method

### ISSUE THREAD

**Issue by SquareBread** [NumeriusNegidius/Context-Search#5]
In Firefox I'm have one keyword search bookmark with very specific url: `data:text/html,<form%20method="post"%20action="http://www.fansubs.ru/search.php"><input%20type="hidden"%20name="query"%20value="%s"/><script>document.forms[0].submit();</script> `. This bookmark is work in address bar, but not work with this extension. Can it possible to fix it?

**Comment by NumeriusNegidius** [comment]
Keyword bookmarks for forms using POST method should be supported if the WebExtensions spec (for browser.tabs.create or smilar) supports it.

**Comment by SquareBread** [comment]
Then, looks like, it's [impossible now.](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/tabs/create)
> For security reasons, in Firefox, this may not be a privileged URL. So passing any of the following URLs will fail: data: URLs

It's sad. Thanks for the reply.

**Comment by NumeriusNegidius** [comment]
This would require the browser.bookmarks API to expose the bookmarks POST state and the form's input parameters. I agree this seems impossible right now. 

Thankfully, search engines using POST are rare, since it is not what POST is intended for. 

I'm closing this issue for now since it is kind of an edge case and I doubt Mozilla will ever expose this information in browser.bookmarks.
