### ISSUE TITLE
using keyword to context search, or searching for search engines. (Feature request)

### ISSUE THREAD

**Issue by brain8891** [NumeriusNegidius/Context-Search#69]
after selecting the text > right clicking on it > And then right clicked on [Search for" example text..."] > then typed one of the keywords of the search engines in "Searches" folder > then hit enter>  it would search in with that search engine. 

Reason:
If a user have many websites organized in many folders, it will help them context search faster. Please continue to the example.

Example: 
0- having abbreviations.com added to the "Searches" folder with "Abrv" as a keyword.
1- Selecting "TLDR" on a webpage.
2- right clicking on it.
3- right clicking on [Search for" TLDR"].
4-  a small preview window appears.
5-  typing abrv
6- hitting enter
7- going to https://www.abbreviations.com/serp.php?st=TLDR

Additionally, it should also suggest search engines without a keyword, for example if you typed "Ab" it would suggest "ab....com "

How it is for me right now:

I have to select > click on [Search for "TLDR"]> Lingual>English>Dictionaries> abbreviations.com

Thank you for your hard work.

**Comment by NumeriusNegidius** [comment]
Thanks for the proposal. This seems a bit convoluted IMO, and especially for those that doesn't have a ton of search engines and/or doesn't remember the keywords. Since I believe this feature would appeal only to a handful of users, I'm hesitant to add more complexity to the code with this feature.

Cheers!
